# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|
  config.vm.provision "shell", path: "startup.sh"
  config.vm.define "dbhost" do |dbhost|
    dbhost.vm.box = "centos/7"
    dbhost.vm.hostname = "dbhost.eduami.org"
    dbhost.vm.network "private_network", ip: "192.168.50.20"
    config.vm.network "forwarded_port", guest: 3306, host: 3306
    dbhost.vm.provider "virtualbox" do |vb|
      vb.name = "dbhost"
      vb.memory = 1024
      vb.cpus = 1
    end
  end
end
